/**
 * Telegram bot config for `createTelegram` (§7).
 */

export interface TelegramWebhookConfig {
  /** Public domain for Telegram to POST updates to (required by Telegraf). */
  domain: string;
  /** Local listen port. Defaults to Telegraf's default (80/443). */
  port?: number;
  /** Webhook URL path; auto-generated by Telegraf if omitted. */
  path?: string;
  /** Bound host for the local webhook server. */
  host?: string;
  /**
   * Secret token sent in `X-Telegram-Bot-Api-Secret-Token`.
   * Validated by Telegraf when set.
   */
  secretToken?: string;
}

export interface TelegramConfig {
  botToken: string;
  /**
   * Single allow-listed chat id (§7 — "single eternal chat").
   * Compared as a string against `String(telegramChatId)`.
   */
  chatId: string;
  /**
   * When set, `start()` launches Telegraf in webhook mode via its bundled
   * server (`bot.launch({ webhook })`) — no separate HTTP framework.
   * When omitted, long-polling is used (`bot.launch()`).
   */
  webhook?: TelegramWebhookConfig;
}
